[project]
name = "localstack_ml_sandbox"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "scikit-learn",
    "boto3",
    "localstack-client",
    "awscli-local",
    "pandas",
    "localstack",
]

[tool.uv]
dev-dependencies = [
    "pytest",
]
